### PR TITLE
Disable login form validation

### LINKED ISSUE #3: Does not work in WordPress 6.3 anymore
See: https://core.trac.wordpress.org/changeset/55953 and https://core.trac.wordpress.org/ticket/32510

### PR DESCRIPTION
**Pull request by szepeviktor**
@chesio Could you please review it?

The login footer is a safer place to run JS as the form element is complete there.

Resolves #3

### CODE REVIEW

**Comment by szepeviktor** [comment]
Should we target [`#loginform`](https://github.com/WordPress/wordpress-develop/blob/6.3/src/wp-login.php#L1425)? What if someone adds a second form to the login page?

**Comment by chesio** [comment]
> Should we target [`#loginform`](https://github.com/WordPress/wordpress-develop/blob/6.3/src/wp-login.php#L1425)? What if someone adds a second form to the login page?

Good point, something like this is likely safer:
```html
<script>document.getElementById("loginform").setAttribute("novalidate", "");</script>
```

And if someone messes with login form element ID, then he/she deserves to suffer ;-)

**Comment by chesio** [comment]
> The login footer is a safer place to run JS as the form element is complete there.

The drawback is that the `login_footer()` method that fires `login_footer` action is included for every type of wp-login.php form (like forgotten password for example).

**Comment by szepeviktor** [comment]
All right.
Then we have a free way for every kind of login page!

**Comment by chesio** [comment]
The form IDs are different, so it's just that the snippet will do nothing there :-)

**Pull request merged**
